### ISSUE TITLE
Jenkins Failure - Possible Timeout of process / Lack of Resources

### ISSUE THREAD

**Issue by MartynBSpooner** [ONS-OpenData/ONS-Trade-in-goods#1]
Jenkins Failure - Possible Timeout of process / Lack of Resources
Will need further investigation, some stages taking over 1 day to fail.

**Comment by ajtucker** [comment]
Digging into this a little, I realized that this dataset is the huge one we were given to see whether the process and the database could cope.

After some optimisations using Pandas categoricals (think string pooling), the transformation runs fine in less than 5 minutes, though it outputs around 15 million observations!

In order to cope with uploading this through PMD, we have split the output files into more manageable chunks and upload them one at a time, which takes a few hours.

At the same time, validating this many observations also takes a while using `csvlint`, so we restricted to just sanity checking the first chunk for now.

In the end, we managed to run the Jenkins pipeline to the point where it managed to upload all the data, but not publish it. We then manually published the results in PMD by running some low level database commands IIRC.

For this reason, the Jenkins pipeline is currently disabled until a) PMD moves to "O(1) publication", b) we need to update the data, c) we figure out how to validate better and d) the CSV to RDF and add to database process is a bit more optimised.

Closing this issue for now and I'll raise the other issues separately.
